---
image: python:3

before_script:
  - pip install yamllint
  - python --version 
  - pip --version

test:
  script:
    - yamllint -c .yamllint_conf .
    - mv secrets_CI.yaml secrets.yaml
    - pip install homeassistant
    - hass -c . --script check_config --info all
