---
image: python:3

stages:
  - linting
  - configtest

.ha: &ha
  stage: configtest
  variables:
    PYTHONPATH: "/usr/src/app:$PYTHONPATH"
  before_script:
    - python -m homeassistant --version
    - cp config/secrets_CI.yaml config/secrets.yaml
  script:
    - python -m homeassistant --config config/ --script check_config --info all

yamllint:
  stage: linting
  image: sdesbure/yamllint
  before_script:
    - yamllint --version
    - cat .yamllint_conf
  script:
    - yamllint -c .yamllint_conf config/ esphome/*.yaml

ha-configtest:
  <<: *ha
  image:
    name: homeassistant/home-assistant:latest
    entrypoint: [""]

ha-rc-configtest:
  <<: *ha
  image:
    name: homeassistant/home-assistant:rc
    entrypoint: [""]
  allow_failure: true
