- platform: mjpeg
  mjpeg_url: !secret raspi_camera 
  name: "Balkonblick"

## android IP cam
- platform: mjpeg
  name: "Android App"
  #still_image_url: http://IP/
  mjpeg_url: !secret android_ipc_path
  username: !secret android_ipc_user
  password: !secret android_ipc_pass


