---
# - platform: mjpeg
#   mjpeg_url: !secret raspi_camera
#   name: "Raspy Cam"

# android IP cam
# - platform: mjpeg
#   name: "Balkonblick"
#   # still_image_url: !secret android_ipc_photo_path
#   mjpeg_url: !secret android_ipc_video_path
#   username: !secret android_ipc_user
#   password: !secret android_ipc_pass

- platform: mjpeg
  name: "Freibad Fürstenfeld"
  mjpeg_url: "http://84.115.191.3/mjpg/video.mjpg?COUNTER"

# - platform: mjpeg
#   name: "Dornbirn"
#   mjpeg_url: "http://212.51.246.241/mjpg/video.mjpg?COUNTER"

# - platform: generic
#   name: "Karren"
#   still_image_url: "https://www.foto-webcam.eu/webcam/dornbirn/{{ now().year }}/{{ now().month }}/{{ now().day }}/{{ now().hour }}{{ now().minute//10 | default(0) }}0_lm.jpg"
#   # limit_refetch_to_url_change: true
#   ## framerate: 0.003

- platform: generic
  name: Unwetter_Stmk
  still_image_url: http://unwetter.wetteralarm.at/images/map/steiermark_index.png
  #  content_type: image/png
  #  framerate: 0.05
