- platform: mjpeg
  mjpeg_url: !secret raspi_camera 
  name: "Raspy Cam"

## android IP cam
- platform: mjpeg
  name: "Balkonblick"
  #still_image_url: http://IP/
  mjpeg_url: !secret android_ipc_path
  username: !secret android_ipc_user
  password: !secret android_ipc_pass

- android_ip_cam:
  - host: !secret android_ip_cam_ip
    name: "Balkon"
    username: !secret android_ipc_user
    password: !secret android_ipc_pass
    sensors: 
      - light
