---
- alias: Alarm for tampering with door sensor
  initial_state: true
  trigger:
    platform: state
    entity_id: binary_sensor.wohnungstuer_burglar
    from: 'off'
    to: 'on'
  condition:
    # prevent false positives after reboot/restart of HomeAssistant
    - condition: numeric_state
      entity_id: sensor.uptime_min
      above: 0.5
  action:
    - service: notify.sms_to_flo
      data:
        message: "Alarm! Someone tampered with the door sensor"
    - service: notify.jabber
      data:
        title: ""
        message: "Alarm! Someone tampered with the door sensor"

- alias: Alarm for door opening when no-one is home
  initial_state: true
  trigger:
    platform: state
    entity_id: binary_sensor.wohnungstuer
    from: 'off'
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        # entity_id: group.all_devices
        entity_id: group.all_devices_presence
        # state: "not_home"
        state: "off"
  action:
    - service: notify.sms_to_flo
      data:
        message: "Alarm! Door openend and no-one home!!"
    - service: notify.jabber
      data:
        title: "ALARM!"
        message: "Door openend and no-one home!!"
