---
- alias: "Button 1 All off"
  initial_state: true
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d000128afa3
      click_type: long_click_press
  action:
    service: scene.turn_on
    entity_id: scene.all_off

- alias: "Button 1 mute mpd radio"
  initial_state: true
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d000128afa3
      click_type: single
  action:
    service: media_player.volume_mute
    data_template:
      entity_id: media_player.mpd
      is_volume_muted: "{{ not state_attr('media_player.mpd','is_volume_muted') }}"

- alias: "Button 1 mute for 1 minutes 40 secs"
  initial_state: true
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d000128afa3
      click_type: double
  action:
    - service: media_player.volume_mute
      data:
        entity_id: media_player.mpd
        is_volume_muted: true
    - delay: 00:01:40
    - service: media_player.volume_mute
      data:
        entity_id: media_player.mpd
        is_volume_muted: false
