---
- id: battery alert
  alias: 'Battery Alert'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: sensor.battery_status
  condition:
    - condition: template
      value_template: >
        {{ trigger.to_state.state | length > 0 }}
  action:
    # - service: persistent_notification.create
    #   data_template:
    #     title: Low Battery levels
    #     notification_id: low-battery-alert
    #     message: >
    #       Check battery: {{ states('sensor.battery_status') }}
    - service: notify.jabber
      data_template:
        title: "Battery status low"
        message: >
          Check battery: {{ states('sensor.battery_status') }}
