---
- alias: "coming home (turn on WZ light)"
  initial_state: true
  hide_entity: false
  trigger:
    platform: state
    entity_id: sensor.flo_home
    to: 'home'
  condition:
    condition: and
    conditions:
      - condition: sun
        after: sunset
        after_offset: "-00:30:00"
      - condition: state
        entity_id: media_player.kodi
        state: idle
  action:
    - service: homeassistant.turn_on
      entity_id:
        - switch.tradfri_outlet
    - service: light.turn_on
      data:
        entity_id: light.tradfri_bulb_e27_ws_opal_980lm
        color_temp: 340
        brightness: 255
        transition: 60
