---
- alias: "LEDstrip Input Effect"
  initial_state: true
  hide_entity: false
  trigger:
    - platform: state
      entity_id: input_select.ledstrip_effect
  action:
    - service: mqtt.publish
      data_template:
        topic: "esp8266/mqttstrip/seteffect"
        payload: '{{ trigger.to_state.state | string }}'

- alias: "LEDstrip Animation Speed"
  initial_state: true
  hide_entity: false
  trigger:
    - platform: state
      entity_id: input_number.ledstrip_animation_speed
  action:
    - service: mqtt.publish
      data_template:
        topic: "esp8266/mqttstrip/setanimationspeed"
        payload: '{{ trigger.to_state.state | int }}'

- alias: "wordclock update"
  initial_state: true
  hide_entity: false
  trigger:
    - platform: state
      entity_id: input_select.wordclock_effect
  action:
    - service: mqtt.publish
      data_template:
        topic: "/wordclock-01201b00/wordclock/command"
        payload: '{{ trigger.to_state.state | string }}'
