---
- alias: "Update info"
  trigger:
    platform: state
    entity_id: binary_sensor.updater
    to: 'on'
  action:
    service: notify.jabber
    data:
      title: "Update: "
      message: "New Home Assistant version available ({{states.updater.updater.state }})"
