---
- alias: "lights out in the living room"
  initial_state: true
  trigger:
    - platform: time
      at: '01:50'
  action:
    - service: scene.turn_on
      entity_id: scene.all_off
    - service: media_player.media_pause
      entity_id: media_player.kodi
    - service: media_player.turn_off
      entity_id: media_player.tv
