---
- alias: Outside temperature diff
  initial_state: true
  hide_entity: false
  trigger:
    platform: time_pattern
    minutes: '/1'
  action:
    - service: input_number.set_value
      data_template:
        entity_id: "input_number.outside_temp_diff"
        # red 0, blue 240
        value: |
          {%- set outside = states('sensor.aussen_temp')|default(0)|float(0) -%}
          {%- set inside = states('sensor.wz_temp')|default(0)|float(0) -%}
          {%- if outside < inside -%}
          240
          {%- else -%}
          0
          {%- endif -%}

- alias: Outside temperature status led
  initial_state: true
  hide_entity: false
  trigger:
    - platform: time_pattern
      minutes: '/1'
    - platform: state
      entity_id: input_number.outside_temp_diff
  action:
    - service: light.turn_on
      data_template:
        entity_id: "light.status_led_1"
        effect: "None"
        hs_color:
          - "{{ states('input_number.outside_temp_diff')|default(120)|int }}"
          - 90

#         rgb_color:
#           - {{ r }}
#           - {{ g }}
#           - {{ b }}
#           # {%- if 0 < 1 -%}
#           # {{ [0, 30, 150] | list}}
#           # {%- else -%}
#           # {{ [80, 20, 0] | list}}
#           # {%- endif -%}
#
# # >
# # {%- set outside = states('sensor.aussen_temp')|default(0)|float(0) -%}
# # {%- set inside = states('sensor.wz_temp')|default(0)|float(0) -%}
# # {%- if outside < inside -%}
# # '#0050ff'
# # {%- else -%}
# # '#dd0000'
# # {%- endif -%}
#
# # [90,0,0]
# # [0,50,200]
# # data:
# #   entity_id: light.status_led_1
# #   rgb_color: [90,0,0]
# #   effect: None
#
# # {% set outside = states('sensor.aussen_temp')|default(0)|float(0) %}
# # {% set inside = states('sensor.wz_temp')|default(0)|float(0) %}
# # {%- if outside < inside -%}
# # [90,0,0]
#   # brightness: 254
#   # {% set outside = states.sensor.aussen_temp.state|float(0)|default(0) %}
#   # {% set inside = states.sensor.wz_temp.state|float(0)|default(0) %}
#
# # condition:
# #   - condition: state
# #     entity_id: sensor.flo_home
# #     state: 'home'
