---
- alias: Outside temperature diff
  initial_state: true
  hide_entity: false
  trigger:
    platform: time_pattern
    minutes: '/1'
  action:
    - service: input_number.set_value
      data_template:
        entity_id: "input_number.outside_temp_diff"
        # red 0, blue 240
        value: |
          {%- set outside = states('sensor.aussen_temp')|default(0)|float(0) -%}
          {%- set inside = states('sensor.wz_temp')|default(0)|float(0) -%}
          {%- if outside < inside -%}
          240
          {%- else -%}
          0
          {%- endif -%}

- alias: Outside temperature status led
  initial_state: true
  hide_entity: false
  trigger:
    - platform: time_pattern
      minutes: '/1'
    - platform: state
      entity_id: input_number.outside_temp_diff
  action:
    - service: light.turn_on
      data_template:
        entity_id: "light.status_led_1"
        effect: "None"
        brightness: 90
        hs_color:
          - "{{ states('input_number.outside_temp_diff')|default(120)|int }}"
          - 90
