---
# You can read about how to upgrade an ordinary smoke detector
# into smart smoke detector in my blogpost:
# https://blog.flo.cx/s/bu
- alias: "smoke alarm"
  initial_state: true
  trigger:
    platform: mqtt
    topic: "/br38/smoke/vorzimmer"
    payload: "smoke"
  condition:
    - condition: template
      value_template: >
        {%- if states.automation.smoke_alarm.attributes.last_triggered -%}
          {{ (as_timestamp(now()) - as_timestamp(states.automation.smoke_alarm.attributes.last_triggered)) > 150 }}
        {%- else -%}
          true
        {%- endif -%}
  action:
    # TODO add fancier notifications
    - service: switch.turn_on
      entity_id: switch.rundumleuchte
    - service: homeassistant.turn_on
      entity_id: group.alarm_all_lights
    - service: notify.sms_to_flo
      data:
        message: "Alarm! Smoke detected!"
    - service: notify.jabber
      data:
        title: "Alarm!"
        message: "Smoke detected!"

- alias: "reset smoke alarm"
  initial_state: true
  trigger:
    platform: mqtt
    topic: "/br38/smoke/vorzimmer"
    payload: "smoke"
  action:
    - delay: '00:00:27'
    - service: mqtt.publish
      data:
        topic: "/br38/smoke/vorzimmer"
        payload: "OFF"
