---
- alias: "Test Automation"
  initial_state: false
  trigger:
    platform: state
    entity_id: input_boolean.testinger
    to: 'on'
  # condition:
  # #   # condition: and
  # #   # conditions:
  # #     # only continue if media_player is not playing
  # #     # - condition: template
  # #     #   value_template: '{{ not is_state("media_player.kodi", "playing") }}'
  # #     # only if Flo is home
  #   - condition: state
  #     entity_id: sensor.flo_home
  #     state: "home"
  action:
    service: light.turn_on
    data:
      entity_id: light.tradfri_bulb_e27_ws_opal_980lm
      color_temp: 441
      brightness: 254
      transition: 13

- alias: "Test Automation2"
  initial_state: false
  trigger:
    platform: state
    entity_id: input_boolean.testinger
    to: 'off'
  # condition:
  #   # condition: and
  #   # conditions:
  #     # only if Flo is home
  #   condition: state
  #   entity_id: sensor.flo_home
  #   state: "home"
  action:
    service: homeassistant.turn_off
    entity_id: light.tradfri_bulb_e27_ws_opal_980lm
    # transition: 30
