---
# - alias: "Sunset 2"
#   initial_state: false
#   trigger:
#     platform: numeric_state
#     entity_id: sensor.balkon_light_level
#     below: 20
#     for:
#       minutes: 5
#   condition:
#     condition: and
#     conditions:
#       # make sure the script continues only around sunset
#       # must be
#       # after 20 min before sunset
#       - condition: sun
#         after: sunset
#         after_offset: "-00:20:00"
#       # and
#       # before 20 min after sunset
#       - condition: sun
#         before: sunset
#         before_offset: "00:20:00"
#       # only fire once in 40 min (2400 secs)
#       - condition: template
#         value_template: >
#           {%- if states.automation.sunset_2.attributes.last_triggered -%}
#             {{ (as_timestamp(now()) - as_timestamp(states.automation.sunset_2.attributes.last_triggered)) > 2400 }}
#           {%- else -%}
#             true
#           {%- endif -%}
#       # only continue if media_player is not playing
#       - condition: template
#         value_template: '{{ not is_state("media_player.kodi", "playing") }}'
#       # only if Flo is home
#       - condition: state
#         entity_id: sensor.flo_home
#         state: "home"
#       # both lights need to be off
#       - condition: state
#         entity_id: light.tradfri_bulb_e27_ws_opal_980lm
#         state: 'off'
#       - condition: state
#         entity_id: switch.tradfri_outlet
#         state: 'off'
#   action:
#     service: script.sunset
