---
- alias: "Sunset"
  initial_state: true
  trigger:
    platform: sun
    event: sunset
    # summer
    # offset: "-00:15:00"
    # winter
    offset: "-00:25:00"
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: >
          {%- if states.automation.sunset.attributes.last_triggered -%}
            {{ (as_timestamp(now()) - as_timestamp(states.automation.sunset.attributes.last_triggered)) > 150 }}
          {%- else -%}
            true
          {%- endif -%}
      # only continue if media_player is not playing
      - condition: template
        value_template: '{{ not is_state("media_player.osmc_waldo", "playing") }}'
      - condition: state
        # entity_id: group.all_devices
        entity_id: sensor.flo_home
        state: "home"
      # both lights need to be off
      - condition: state
        entity_id: light.tradfri_bulb_e27_ws_opal_980lm
        state: 'off'
      - condition: state
        entity_id: switch.tradfri_outlet
        state: 'off'
  action:
    service: script.sunset
