# ---
# - alias: "Tree on"
#   initial_state: false
#   trigger:
#     platform: time
#     hours: 16
#     minutes: 55
#     seconds: 10
#   condition:
#     condition: state
#     entity_id: group.all_devices
#     state: "home"
#   action:
#     - service: homeassistant.turn_on
#       entity_id:
#         - switch.christbaum
#     # - service: notify.jabber
#     #   data:
#     #     title: ""
#     #     message: "Activated Christmas Tree"
