---
- alias: "warn no one home but lights on"
  initial_state: true
  trigger:
    # when no one is home OR
    - platform: state
      entity_id: group.all_devices_presence
      to: 'not_home'
      for:
        minutes: 10
        seconds: 5
    # when lights are on
    - platform: state
      entity_id: group.warn_all_lights
      to: 'on'
      for:
        minutes: 10
        seconds: 5
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.all_devices_presence
        state: "not_home"
      - condition: state
        entity_id: group.warn_all_lights
        state: "on"
  action:
    service: notify.jabber
    data:
      message: "No one home, but lights are on!"
