---
- platform: openweathermap
  api_key: !secret owm_api_key
  forecast: 1
  monitored_conditions:
    - weather
    - temperature
    - wind_speed
    - humidity
    - pressure
    - clouds
    - rain
    - snow
