---
# pick the current radio station from input_select and output the type and URL
# as sensor data for the automation to pick up.
- platform: template
  sensors:
    radio_data:
      value_template: >
        {% set radio =
        {
          'Soundportal': ('Soundportal', 'playlist', 'https://www.stream24.net/tune-in/r8235.pls'),
          'Welle1': ('Welle1', 'playlist', 'http://live.welle1.at:9128/'),
          'loungeFM': ('loungeFM', 'channel', 'http://188.138.9.183/digital.mp3'),
          'Austria Rock Radio': ('Austria Rock Radio', 'channel', 'http://stream5.liferadio.at/'),
          'Helsinki': ('Helsinki', 'tunein', 's17838'),
          'Ö1': ('Ö1', 'playlist', 'http://mp3stream3.apasf.apa.at:8000/listen.pls'),
          'Ö3': ('ö3', 'playlist', 'http://mp3stream7.apasf.apa.at:8000/listen.pls'),
          'FM4': ('FM4', 'playlist', 'http://mp3stream1.apasf.apa.at:8000/listen.pls'),
          'Kronehit': ('Kronehit', 'tunein', 's15570'),
          'Antenne': ('Antenne', 'tunein', 's1139'),
          'Film Music - Movie Scores - Movie Soundtracks': ('Film Music', 'tunein', 's302173'),
          'GotRadio The Big Score': ('GotRadio The Big Score', 'tunein', 's49696'),
          'ClassicFM': ('ClassicFM', 'tunein', 's8439'),
          'BBC1': ('BBC1', 'tunein', 's24939'),
          'BBC2': ('BBC2', 'tunein', 's24940'),
          'Kinderlieder 1-2-3': ('Kinderlieder 1-2-3', 'tunein', 's260986'),
          'Kinderradio (D)': ('Kinderradio (D)', 'tunein', 's230573'),
          'Omega 105.1 FM (Costa Rica)': ('Omega 105.1 FM (Costa Rica)', 'tunein', 's82770'),
        }
        %}
        {{ radio[states('input_select.radio_stations')][1] }}|{{ radio[states('input_select.radio_stations')][2] }}
