---
- platform: mqtt
  state_topic: "wallpanel/sensor/battery"
  name: "Wallpanel Battery"
  qos: 0
  unit_of_measurement: "%"
  value_template: "{{ value_json.value | round(1) }}"

- platform: mqtt
  state_topic: "wallpanel/sensor/qrcode"
  name: "QR Code"
  value_template: ''

