- platform: template
  sensors:
    flo_home:
      friendly_name: "Flo home"
      value_template: >-
        {%- if is_state('binary_sensor.flo_home', 'on') -%}
          home
        {%- else -%}
          not_home
        {%- endif -%}
