- platform: mqtt
  state_topic: !secret flo_phone_topic
  name: !secret flo_phone_label
  unit_of_measurement: "%"
  value_template: "{{ value_json.batt }}"
  icon_template: >
    {% set battery_level = value_json.batt | default(0) | int %}
    {% set battery_round = (battery_level / 10) |int * 10 %}
    {% if battery_round >= 100 %}
      mdi:battery
    {% elif battery_round > 0 %}
      mdi:battery-{{ battery_round }}
    {% else %}
      mdi:battery-alert
    {% endif %}
