- platform: template
  sensors:
    tine_home:
      friendly_name: "Tine home"
      value_template: >-
        {%- if is_state('binary_sensor.tine_home', 'on') -%}
          home
        {%- else -%}
          not_home
        {%- endif -%}
