---
- platform: template
  sensors:
    xiaomi_vacuum_battery:
      friendly_name: "Akku"
      unit_of_measurement: '%'
      value_template: '{{ states.vacuum.xiaomi_vacuum_cleaner.attributes.battery_level|default(None) }}'
      icon_template: >
        {% set battery_icon = states.vacuum.xiaomi_vacuum_cleaner.attributes.battery_icon %}
        {{ battery_icon }}

- platform: template
  sensors:
    xiaomi_vacuum_fan_speed:
      friendly_name: "Saugstärke"
      value_template: '{{ states.vacuum.xiaomi_vacuum_cleaner.attributes.fan_speed }}'
      icon_template: '{{ "mdi:fan" }}'

- platform: template
  sensors:
    xiaomi_vacuum_status:
      friendly_name: "Status"
      value_template: '{{ states.vacuum.xiaomi_vacuum_cleaner.attributes.status }}'
      icon_template: '{{ "mdi:roomba" }}'

- platform: template
  sensors:
    xiaomi_vacuum_cleaning_time:
      friendly_name: "Putzzeit"
      value_template: '{{ states.vacuum.xiaomi_vacuum_cleaner.attributes.cleaning_time }}'
      icon_template: '{{ "mdi:clock-end" }}'

- platform: template
  sensors:
    xiaomi_vacuum_filter_left:
      friendly_name: "Filterrestzeit"
      unit_of_measurement: 'h'
      value_template: '{{ states.vacuum.xiaomi_vacuum_cleaner.attributes.filter_left }}'
      icon_template: '{{ "mdi:filter-outline" }}'
- platform: template
  sensors:
    xiaomi_vacuum_main_brush_left:
      friendly_name: "Bürstenrestzeit"
      unit_of_measurement: 'h'
      value_template: '{{ states.vacuum.xiaomi_vacuum_cleaner.attributes.main_brush_left }}'
      icon_template: '{{ "mdi:broom" }}'

- platform: template
  sensors:
    xiaomi_vacuum_side_brush_left:
      friendly_name: "Seitenbürstenrestzeit"
      unit_of_measurement: 'h'
      value_template: '{{ states.vacuum.xiaomi_vacuum_cleaner.attributes.side_brush_left }}'
      icon_template: '{{ "mdi:brush" }}'

- platform: template
  sensors:
    xiaomi_vacuum_cleaned_area:
      friendly_name: "gereinigte Fläche"
      unit_of_measurement: 'm²'
      value_template: '{{ states.vacuum.xiaomi_vacuum_cleaner.attributes.cleaned_area }}'
      icon_template: '{{ "mdi:image-area" }}'
