# For info on bayesian sensor see:
# https://home-assistant.io/components/binary_sensor.bayesian/
#
#
# https://github.com/home-assistant/home-assistant/issues/9347
# https://community.home-assistant.io/t/best-implementation-strategy-for-bayesian-binary-sensor/22673/15


- platform: bayesian
  prior: 0.25
  name: "tine_home"
  probability_threshold: 0.85
  observations:
    - entity_id: 'device_tracker.tine_G4'
      prob_given_true: '0.99'
      prob_given_false: '0.05'
      platform: 'state'
      to_state: 'home'
    - entity_id: 'device_tracker.40d32d9c185d'
      prob_given_true: '0.97'
      prob_given_false: '0.5'
      platform: 'state'
      to_state: 'home'
    - entity_id: 'device_tracker.tine_ipad'
      prob_given_true: '0.65'
      prob_given_false: '0.5'
      platform: 'state'
      to_state: 'home'
