- platform: bayesian
  prior: 0.1
  name: "flo_home"
  probability_threshold: 0.75
  observations:
    - entity_id: 'device_tracker.floop3_oneplus3'
      prob_given_true: '0.95'
      prob_given_false: '0.05'
      platform: 'state'
      to_state: 'home'
    - entity_id: 'device_tracker.flo_laptop'
      prob_given_true: '0.8'
      prob_given_false: '0.2'
      platform: 'state'
      to_state: 'home'
    - entity_id: 'media_player.osmcwaldo'
      prob_given_true: '0.6'
      prob_given_false: '0.1'
      platform: 'state'
      to_state: 'playing'
