- platform: template
  sensors:
    wohnungstuer:
      device_class: opening
      friendly_name: 'Wohnungst端r'
      value_template: >-
        {%- if is_state("sensor.tuer1_access_control", "22") -%}
          True
        {%- else -%}
          False
        {%- endif -%}

- platform: template
  sensors:
    wohnzimmerbalkontuer:
      device_class: opening
      friendly_name: 'Wohnzimmerbalkont端r'
      value_template: >-
        {%- if is_state("sensor.tuer2_access_control", "22") -%}
          True
        {%- else -%}
          False
        {%- endif -%}

- platform: template
  sensors:
    kuechenbalkontuer:
      device_class: opening
      friendly_name: 'K端chenbalkont端r'
      value_template: >-
        {%- if is_state("sensor.tuer3_access_control", "22") -%}
          True
        {%- else -%}
          False
        {%- endif -%}
