---
- platform: template
  sensors:
    wohnungstuer:
      device_class: opening
      friendly_name: 'Wohnungstür'
      value_template: >-
        {%- if is_state("sensor.fibaro_system_fgdw002_door_opening_sensor_2_access_control", "22") -%}
          True
        {%- else -%}
          False
        {%- endif -%}

- platform: template
  sensors:
    wohnungstuer_burglar:
      device_class: safety
      friendly_name: 'Wohnungstürsensor Manipulation'
      value_template: >-
        {%- set state = states('sensor.fibaro_system_fgdw002_door_opening_sensor_2_burglar') -%}
        {%- if state == '254' or state == '0' -%}
          False
        {%- else -%}
          True
        {%- endif -%}

- platform: template
  sensors:
    wohnzimmerbalkontuer:
      device_class: opening
      friendly_name: 'Wohnzimmerbalkontür'
      value_template: >-
        {%- if is_state("sensor.tuer2_access_control", "22") -%}
          True
        {%- else -%}
          False
        {%- endif -%}

- platform: template
  sensors:
    kuechenbalkontuer:
      device_class: opening
      friendly_name: 'Küchenbalkontür'
      value_template: >-
        {%- if is_state("sensor.tuer3_access_control", "22") -%}
          True
        {%- else -%}
          False
        {%- endif -%}
