---
homeassistant:
  # Name of the location where Home Assistant is running
  name: !secret name_home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret lat
  longitude: !secret lon
  # Impacts weather/sunrise data
  elevation: 459
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here:
  # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Vienna

  customize: !include customize.yaml

lovelace:
  mode: yaml

system_health:

zone 1:
  name: !secret zone1_name
  latitude: !secret lat
  longitude: !secret lon
  radius: 40

zone 2:
  name: !secret zone2_name
  icon: mdi:factory
  latitude: !secret lat_zone2
  longitude: !secret lon_zone2
  radius: 90

zone 3:
  name: !secret zone3_name
  icon: mdi:castle
  latitude: !secret lat_zone3
  longitude: !secret lon_zone3
  radius: 150

zone 4:
  name: !secret zone4_name
  icon: mdi:wrench
  latitude: !secret lat_zone4
  longitude: !secret lon_zone4
  radius: 40

influxdb:
  host: !secret influx_host
  port: !secret influx_port
  username: !secret influx_user
  password: !secret influx_pass
  ssl: true
  database: hass_db

# Show links to resources in log and frontend
# introduction:

# Enables the frontend
frontend:
  themes: !include themes.yaml
# panel_custom:
#   - name: Floorplan
#     sidebar_title: Floorplan
#     sidebar_icon: mdi:home
#     url_path: floorplan
#     config: !include floorplan.yaml
#
#


weblink:
  entities:
    - name: Mopidy
      url: !secret mopidy_webclient_url
    - name: Grafana
      url: !secret grafana_link_url

http:
# use_x_forwarded_for: true
# ip_ban_enabled: false
# login_attempts_threshold: 5

# auth_providers:
#  - type: legacy_api_password
#    api_password: !secret api_password

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

config:

# Allows you to issue voice commands from the frontend in enabled browsers
# conversation:

# Enables support for tracking state changes over time.
history:

map:

stream:

# NoSQL really pounded the SD-card of my Raspberry Pi
# trying external USB-stick
recorder:
  # db_url: !secret external_sqlite_url
  db_url: !secret postgres_url
  purge_keep_days: 5
  purge_interval: 1
# db_url: !secret mariadb_url

# View all events in a logbook
logbook:

# Track the sun
sun:

shopping_list:

# shell_command: !include shell_command.yaml
switch: !include switches.yaml

# Groups
group: !include groups.yaml

camera: !include camera.yaml

tts:
  - platform: picotts
    language: 'de-DE'

mqtt:
  broker: localhost
  port: 1883
  username: !secret mqtt_user
  password: !secret mqtt_pwd
  discovery: true
  discovery_prefix: homeassistant

tradfri:
  host: !secret tradfri_ip
# do not use the API_KEY from v0.57 and above!
#  api_key: !secret tradfri_security_key

zwave:
  usb_path: /dev/ttyACM0
  # config_path: /srv/homeassistant/src/open-zwave-control-panel/config
  # config_path:
  # /usr/local/lib/python3.4/dist-packages/libopenzwave-0.3.1-py3.4-linux-armv7l.egg/config/

xiaomi_aqara:
  gateways:
    - mac: !secret xiaomi_gw_mac
      key: !secret xiaomi_gw_key

# temp disable
# vacuum:
#   - platform: xiaomi_miio
#     host: 192.168.3.138
#     token: !secret xiaomi_vacuum_key

# android_ip_webcam:
#   - host: !secret android_ip_cam_ip
#     name: "Balkon"
#     username: !secret android_ipc_user
#     password: !secret android_ipc_pass
#     scan_interval: 60
#     sensors:
#       - light

binary_sensor: !include_dir_merge_list binary_sensors/

sensor: !include_dir_merge_list sensors/
# sensor 1:
#   platform: yr

media_player: !include media_player.yaml

device_tracker: !include device_tracker.yaml

# ##### fancy lights ######
light: !include lights.yaml

# light:
# - platform: mqtt
#   name: "WZ Vitrine"
#   friendly_name: "Vitrine"
#   # command_topic: "/br38/sonoff/switch/SONOFF_A751BC/relay/0"
#   # state_topic: "/br38/sonoff/switch/SONOFF_A751BC/relay/0"
#   command_topic: "cmnd/DVES_33C0B2/POWER"
#   state_topic: "stat/DVES_33C0B2/POWER"
#   rgb_command_topic: "cmnd/DVES_33C0B2/Color"
#   rgb_state_topic: "stat/DVES_33C0B2/Color"
#   brightness_command_topic: "cmnd/DVES_33C0B2/Dimmer"
#   brightness_state_topic: "stat/DVES_33C0B2/Dimmer"
#   brightness_scale: 100
#   payload_on: "ON"
#   payload_off: "OFF"
#   optimistic: false
#   # retain: true
#
# - platform: mqtt
#   name: "LEDstrip"
#   command_topic: "esp8266/mqttstrip/setpower"
#   state_topic: "esp8266/mqttstrip/setpowerpub"
#   rgb_state_topic: "esp8266/mqttstrip/setcolorpub"
#   rgb_command_topic: "esp8266/mqttstrip/setcolor"
#   brightness_state_topic: "esp8266/mqttstrip/setbrightnesspub"
#   brightness_command_topic: "esp8266/mqttstrip/setbrightness"
#   optimistic: false
#   retain: true
# # - platform: mqtt
# #   name: 'B1 Light TEST'
# #   state_topic: '/br38/sonoff/light/SONOFF_B1_8677F2/relay/0'
# #   command_topic: '/br38/sonoff/light/SONOFF_B1_8677F2/relay/0/set'
# #   payload_on: 1
# #   payload_off: 0
# #   rgb_state_topic: '/br38/sonoff/light/SONOFF_B1_8677F2/color'
# #   rgb_command_topic: '/br38/sonoff/light/SONOFF_B1_8677F2/color/set'
# #   rgb: true
# #   optimistic: false
# #   color_temp: true
# #   color_temp_command_topic: '/br38/sonoff/light/SONOFF_B1_8677F2/mired/set'
# #   brightness: true
# #   brightness_command_topic:
# # '/br38/sonoff/light/SONOFF_B1_8677F2/brightness/set'
# #   brightness_state_topic: '/br38/sonoff/light/SONOFF_B1_8677F2/brightness'
# #   white_value: true
# #   white_value_command_topic:
# # '/br38/sonoff/light/SONOFF_B1_8677F2/channel/3/set'
# #   white_value_state_topic: '/br38/sonoff/light/SONOFF_B1_8677F2/channel/3'
#
#
# - platform: mqtt
#   name: "wordclock"
#   command_topic: "/wordclock-01201b00/wordclock/command"
#   rgb_state_topic: "/wordclock-01201b00/wordclock/color"
#   rgb_command_topic: "/wordclock-01201b00/wordclock/color"
#   brightness_command_topic: "/wordclock-01201b00/wordclock/brightness"
#   retain: true


input_select:
  ledstrip_effect:
    name: LEDstrip Effect
    options:
      - "Solid"
      - "BPM"
      - "Confetti"
      - "Cyclon Rainbow"
      - "Dots"
      - "Fire"
      - "Glitter"
      - "Juggle"
      - "Lightning"
      - "Noise"
      - "Police All"
      - "Police One"
      - "Rainbow"
      - "Ripple"
      - "Sinelon"
      - "Solid"
      - "Twinkle"
    initial: "Solid"
  wordclock_effect:
    name: wordclock effect
    options:
      - "clock"
      - "color_sparcle"
      - "blue_sparcle"
    initial: "clock"
  radio_stations:
    name: Radio Stations
    options:
      # - "Ö3___tunein:s15552"
      - "Ö3:playlist___|http://mp3stream7.apasf.apa.at:8000/listen.pls"
      - "Kronehit___:tunein:s15570"
      - "Ö1___:tunein:s15555"
      # - "loungeFM___:tunein:s177755"
      - "loungeFM___|http://188.138.9.183/digital.mp3"
      - "Helsinki___:tunein:s17838"
      - "Soundportal___:tunein:s25852"
      - "Antenne___:tunein:s1139"
      # - "FM4___:tunein:s8235"
      - "FM4___:playlist|http://mp3stream1.apasf.apa.at:8000/listen.pls"
      - "Welle1___:tunein:s149491"
      - "BBC1___:tunein:s24939"
      - "BBC2___:tunein:s24940"
      - "---"
      - "Austria Rock Radio |http://stream5.liferadio.at/"
      - "Film Music - Movie Scores - Movie Soundtracks___:tunein:s302173"
      - "GotRadio The Big Score___:tunein:s49696"
      - "ClassicFM___:tunein:s8439"
      - "Kinderlieder 1-2-3___:tunein:s260986"
      - "Kinderradio (D)___:tunein:s230573"
      - "Omega 105.1 FM (Costa Rica)___:tunein:s82770"
      # - "Radio Pucki:s101757"
      # - "Radio TEDDY:s80044"


# input_slider:
input_number:
  ledstrip_animation_speed:
    name: LEDstrip Animation Speed
    initial: 150
    min: 1
    max: 150
    step: 10

automation 12:
  - alias: "LEDstrip Input Effect"
    initial_state: true
    hide_entity: false
    trigger:
      - platform: state
        entity_id: input_select.ledstrip_effect
    action:
      - service: mqtt.publish
        data_template:
          topic: "esp8266/mqttstrip/seteffect"
          payload: '{{ trigger.to_state.state | string }}'

  - alias: "LEDstrip Animation Speed"
    initial_state: true
    hide_entity: false
    trigger:
      - platform: state
        entity_id: input_number.ledstrip_animation_speed
    action:
      - service: mqtt.publish
        data_template:
          topic: "esp8266/mqttstrip/setanimationspeed"
          payload: '{{ trigger.to_state.state | int }}'

  - alias: "wordclock update"
    initial_state: true
    hide_entity: false
    trigger:
      - platform: state
        entity_id: input_select.wordclock_effect
    action:
      - service: mqtt.publish
        data_template:
          topic: "/wordclock-01201b00/wordclock/command"
          payload: '{{ trigger.to_state.state | string }}'

  - alias: "radio select"
    initial_state: true
    hide_entity: false
    trigger:
      - platform: state
        entity_id: input_select.radio_stations
    action:
      - service: media_player.play_media
        data_template:
          entity_id: media_player.mpd
          media_content_id: >
            {% if states('input_select.radio_stations').split(':')[1] is eq 'tunein' %}
              tunein:station:{{ states('input_select.radio_stations').split(':')[2] | string}}
            {% elif states('input_select.radio_stations').split(':')[1] is eq 'pl'%}
              {{ states('input_select.radio_stations').split('|')[1] | string}}
            {% else %}
              {{ states('input_select.radio_stations').split('|')[1] | string}}
            {% endif %}
          media_content_type: >
            {% if states('input_select.radio_stations').split(':')[1] is eq 'playlist' %}
              "playlist"
            {% else %}
              "channel"
            {% endif %}

notify: !include notify.yaml

# new in 0.90, not supported by raspy cam with motioneyeOS
# stream:

scene: !include scenes.yaml

# script: !include_dir_list script/
script: !include_dir_named scripts/

automation: !include_dir_merge_list automations/

# via https://github.com/arsaboo/\
# homeassistant-config/blob/01ed7ded33f7cc64ad878f123d3f2118dd77ba07/configuration.yaml#L288
logger:
  # levels: notset, debug, info, warn, warning, error, fatal, critical
  default: warn
  logs:
    homeassistant.component.notify.yessssms: debug
    homeassistant.component.notify.xmpp: info
    homeassistant.component.device_tracker.gpslogger: info
    homeassistant.core: warn
    miio.device: critical
    homeassistant.components.vacuum.xiaomi_miio: critical
    # supress 'unparsed data' WARNING from AndroidIPCam
    urllib3.connectionpool: critical

input_boolean: !include input_booleans.yaml

input_datetime:
  time_wakeup_lights:
    name: Time for wakeup lights
    has_date: false
    has_time: true
    # initial: "6:43"
