---
homeassistant:
  name: !secret name_home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret lat
  longitude: !secret lon
  elevation: 459
  unit_system: metric
  time_zone: Europe/Vienna

  customize: !include customize.yaml

# configuring lovelace through yaml, not via frontend
lovelace:
  mode: yaml

system_health:

zone: !include zones.yaml

influxdb: !include influx.yaml

# Show links to resources in log and frontend
# introduction:

# Enables the frontend
frontend:
  themes: !include themes.yaml

weblink: !include links.yaml

http:
# use_x_forwarded_for: true
# ip_ban_enabled: false
# login_attempts_threshold: 5

updater:

discovery:

config:

history:

map:

# webcam stream for configured cameras (ui-lovelace.yaml)
stream:

recorder: !include db.yaml

logbook:

sun:

shopping_list:

switch: !include switches.yaml

group: !include groups.yaml

camera: !include camera.yaml

tts:
  - platform: picotts
    language: "de-DE"

mqtt: !include mqtt.yaml

tradfri:
  host: !secret tradfri_ip

zwave:
  usb_path: /dev/ttyACM0
  # config_path: /srv/homeassistant/src/open-zwave-control-panel/config
  # config_path:
  # /usr/local/lib/python3.4/dist-packages/libopenzwave-0.3.1-py3.4-linux-armv7l.egg/config/

xiaomi_aqara:
  gateways:
    - mac: !secret xiaomi_gw_mac
      key: !secret xiaomi_gw_key

# temp disable
# vacuum:
#   - platform: xiaomi_miio
#     host: 192.168.3.138
#     token: !secret xiaomi_vacuum_key

binary_sensor: !include_dir_merge_list binary_sensors/

sensor: !include_dir_merge_list sensors/

media_player: !include media_player.yaml

lock: !include lock.yaml

person:
  - name: Flo
    id: flo0001
    user_id: !secret flo_user_id
    device_trackers:
      - device_tracker.nokia_pnxgam88c1104874_2
      - !secret flo_phone_tracker
      - device_tracker.flo_laptop
      - device_tracker.flo_laptop2
      #   - device_tracker.gpslogger
      # - name: tine
      #   id: tine0001
      #   user_id: !secret tine_user_id

# device_tracker: !include device_tracker.yaml
device_tracker:
  - platform: luci
    host: !secret router_IP
    username: !secret router_user
    password: !secret router_pwd
    track_new_devices: false

    # - platform: gpslogger
    # password: !secret gps_logger_pwd

    # - platform: nmap_tracker
    #   hosts: !secret local_tracking_subnet
    #   exclude: !secret dont_scan_hosts
    #   scan_options: " --privileged -sP "

# ##### fancy lights ######
light: !include lights.yaml

input_select:
  ledstrip_effect:
    name: LEDstrip Effect
    options:
      - "Solid"
      - "BPM"
      - "Confetti"
      - "Cyclon Rainbow"
      - "Dots"
      - "Fire"
      - "Glitter"
      - "Juggle"
      - "Lightning"
      - "Noise"
      - "Police All"
      - "Police One"
      - "Rainbow"
      - "Ripple"
      - "Sinelon"
      - "Solid"
      - "Twinkle"
    initial: "Solid"
  wordclock_effect:
    name: wordclock effect
    options:
      - "clock"
      - "color_sparcle"
      - "blue_sparcle"
    initial: "clock"

  # radio station select. See sensors/radio_stations.yaml for details.
  radio_stations:
    name: Radio Stations
    options:
      - "Soundportal"
      - "Welle1"
      - "loungeFM"
      - "Austria Rock Radio"
      - "Helsinki"
      - "--- ORF ---"
      - "Ö1"
      - "Ö3"
      - "FM4"
      - "---"
      - "Kronehit"
      - "Antenne"
      - "Film Music - Movie Scores - Movie Soundtracks"
      - "GotRadio The Big Score"
      - "ClassicFM"
      - "--- div ---"
      - "BBC1"
      - "BBC2"
      - "Kinderlieder 1-2-3"
      - "Kinderradio (D)"
      - "Omega 105.1 FM (Costa Rica)"

input_number:
  ledstrip_animation_speed:
    name: LEDstrip Animation Speed
    initial: 150
    min: 1
    max: 150
    step: 10
  outside_temp_diff:
    name: Outside to inside temperature difference
    initial: 1
    min: 0
    max: 360

notify: !include notify.yaml

scene: !include scenes.yaml

script: !include_dir_named scripts/

automation: !include_dir_merge_list automations/

logger: !include logging.yaml

input_boolean: !include input_booleans.yaml

input_datetime: !include input_datatime.yaml
