---
homeassistant:
  name: !secret name_home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret lat
  longitude: !secret lon
  elevation: 459
  unit_system: metric
  time_zone: Europe/Vienna

  customize: !include customize.yaml

frontend:
  themes: !include themes.yaml

mobile_app:

# gpslogger integration depends on
cloud:

# configuring lovelace through yaml, not via frontend
lovelace:
  mode: yaml

zone: !include zones.yaml

influxdb: !include influx.yaml

system_health:

http:
# use_x_forwarded_for: true
# ip_ban_enabled: false
# login_attempts_threshold: 5

updater:

discovery:

config:

history:

map:

# webcam stream for configured cameras (ui-lovelace.yaml)
stream:

recorder: !include db.yaml

logbook:

sun:

shopping_list:

switch: !include switches.yaml

group: !include groups.yaml

camera: !include camera.yaml

tts: !include tts.yaml

mqtt: !include mqtt.yaml

tradfri:
  host: !secret tradfri_ip

zwave:
  usb_path: /dev/ttyACM0
  # config_path: /srv/homeassistant/src/open-zwave-control-panel/config
  # config_path:
  # /usr/local/lib/python3.4/dist-packages/libopenzwave-0.3.1-py3.4-linux-armv7l.egg/config/

# removed in 0.112
# xiaomi_aqara:
#   discovery_retry: 5
#   gateways:
#     - mac: !secret xiaomi_gw_mac
#       key: !secret xiaomi_gw_key

# temp disable
# vacuum:
#   - platform: xiaomi_miio
#     host: 192.168.3.138
#     token: !secret xiaomi_vacuum_key

binary_sensor: !include_dir_merge_list binary_sensors/

sensor: !include_dir_merge_list sensors/

media_player: !include media_player.yaml

lock: !include lock.yaml

person: !include person.yaml

device_tracker: !include device_tracker.yaml

input_select: !include input_select.yaml

input_number: !include input_number.yaml

input_text: !include input_text.yaml

light: !include lights.yaml

notify: !include notify.yaml

scene: !include scenes.yaml

script: !include_dir_named scripts/

automation: !include_dir_merge_list automations/

logger: !include logging.yaml

input_boolean: !include input_booleans.yaml

input_datetime: !include input_datetime.yaml
