---
homeassistant:
  # Name of the location where Home Assistant is running
  name: !secret name_home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret lat
  longitude: !secret lon
  # Impacts weather/sunrise data
  elevation: 459
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here:
  # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Vienna

  customize: !include customize.yaml

# configuring lovelace through yaml, not via frontend
lovelace:
  mode: yaml

system_health:

zone 1:
  name: !secret zone1_name
  latitude: !secret lat
  longitude: !secret lon
  radius: 40

zone 2:
  name: !secret zone2_name
  icon: mdi:factory
  latitude: !secret lat_zone2
  longitude: !secret lon_zone2
  radius: 90

zone 3:
  name: !secret zone3_name
  icon: mdi:castle
  latitude: !secret lat_zone3
  longitude: !secret lon_zone3
  radius: 150

zone 4:
  name: !secret zone4_name
  icon: mdi:wrench
  latitude: !secret lat_zone4
  longitude: !secret lon_zone4
  radius: 40

influxdb:
  host: !secret influx_host
  port: !secret influx_port
  username: !secret influx_user
  password: !secret influx_pass
  ssl: true
  database: hass_db

# Show links to resources in log and frontend
# introduction:

# Enables the frontend
frontend:
  themes: !include themes.yaml

weblink:
  entities:
    - name: Mopidy
      url: !secret mopidy_webclient_url
    - name: Grafana
      url: !secret grafana_link_url

http:
# use_x_forwarded_for: true
# ip_ban_enabled: false
# login_attempts_threshold: 5

# auth_providers:
#  - type: legacy_api_password
#    api_password: !secret api_password

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

config:

# Allows you to issue voice commands from the frontend in enabled browsers
# conversation:

# Enables support for tracking state changes over time.
history:

map:

# webcam stream for configured cameras (ui-lovelace.yaml)
stream:

# NoSQL really pounded the SD-card of my Raspberry Pi
# trying external USB-stick didn't work. That failed...
# postgres works much better, with faster startup times.
recorder:
  # db_url: !secret external_sqlite_url
  db_url: !secret postgres_url
  purge_keep_days: 5
  purge_interval: 1
# db_url: !secret mariadb_url

# View all events in a logbook
logbook:

# Track the sun
sun:

shopping_list:

# shell_command: !include shell_command.yaml
switch: !include switches.yaml

# Groups
group: !include groups.yaml

camera: !include camera.yaml

tts:
  - platform: picotts
    language: 'de-DE'

mqtt:
  broker: localhost
  port: 1883
  username: !secret mqtt_user
  password: !secret mqtt_pwd
  discovery: true
  discovery_prefix: homeassistant

tradfri:
  host: !secret tradfri_ip
# do not use the API_KEY from v0.57 and above!
#  api_key: !secret tradfri_security_key

zwave:
  usb_path: /dev/ttyACM0
  # config_path: /srv/homeassistant/src/open-zwave-control-panel/config
  # config_path:
  # /usr/local/lib/python3.4/dist-packages/libopenzwave-0.3.1-py3.4-linux-armv7l.egg/config/

xiaomi_aqara:
  gateways:
    - mac: !secret xiaomi_gw_mac
      key: !secret xiaomi_gw_key

# temp disable
# vacuum:
#   - platform: xiaomi_miio
#     host: 192.168.3.138
#     token: !secret xiaomi_vacuum_key

binary_sensor: !include_dir_merge_list binary_sensors/

sensor: !include_dir_merge_list sensors/

media_player: !include media_player.yaml

lock:
  platform: nuki
  host: !secret nuki_host
  token: !secret nuki_token

person:
  - name: Flo
    id: flo0001
    user_id: !secret flo_user_id
    device_trackers:
      - device_tracker.nokia_pnxgam88c1104874_2
      - !secret flo_phone_tracker
      - device_tracker.flo_laptop
      - device_tracker.flo_laptop2
      #   - device_tracker.gpslogger
      # - name: tine
      #   id: tine0001
      #   user_id: !secret tine_user_id

# device_tracker: !include device_tracker.yaml
device_tracker:
  - platform: luci
    host: !secret router_IP
    username: !secret router_user
    password: !secret router_pwd
    track_new_devices: false

    # - platform: gpslogger
    # password: !secret gps_logger_pwd

    # - platform: nmap_tracker
    #   hosts: !secret local_tracking_subnet
    #   exclude: !secret dont_scan_hosts
    #   scan_options: " --privileged -sP "

# ##### fancy lights ######
light: !include lights.yaml


input_select:
  ledstrip_effect:
    name: LEDstrip Effect
    options:
      - "Solid"
      - "BPM"
      - "Confetti"
      - "Cyclon Rainbow"
      - "Dots"
      - "Fire"
      - "Glitter"
      - "Juggle"
      - "Lightning"
      - "Noise"
      - "Police All"
      - "Police One"
      - "Rainbow"
      - "Ripple"
      - "Sinelon"
      - "Solid"
      - "Twinkle"
    initial: "Solid"
  wordclock_effect:
    name: wordclock effect
    options:
      - "clock"
      - "color_sparcle"
      - "blue_sparcle"
    initial: "clock"
  radio_stations:
    name: Radio Stations
    options:
      # - "Soundportal___:tunein:s25852"
      - "Soundportal___:playlist|https://www.stream24.net/tune-in/r8235.pls"
      # - "Welle1___:tunein:s149491"
      - "Welle1___|http://live.welle1.at:9128/"
      # - "loungeFM___:tunein:s177755"
      - "loungeFM___|http://188.138.9.183/digital.mp3"
      - "Austria Rock Radio |http://stream5.liferadio.at/"
      - "Helsinki___:tunein:s17838"
      - "--- ORF ---"
      # - "Ö1___:tunein:s15555"
      - "Ö1___:playlist|http://mp3stream3.apasf.apa.at:8000/listen.pls"
      # - "Ö3___tunein:s15552"
      - "Ö3___:playlist|http://mp3stream7.apasf.apa.at:8000/listen.pls"
      # - "FM4___:tunein:s8235"
      - "FM4___:playlist|http://mp3stream1.apasf.apa.at:8000/listen.pls"
      - "---"
      - "Kronehit___:tunein:s15570"
      - "Antenne___:tunein:s1139"
      - "--- Classic ---"
      - "Film Music - Movie Scores - Movie Soundtracks___:tunein:s302173"
      - "GotRadio The Big Score___:tunein:s49696"
      - "ClassicFM___:tunein:s8439"
      - "--- div ---"
      - "BBC1___:tunein:s24939"
      - "BBC2___:tunein:s24940"
      - "Kinderlieder 1-2-3___:tunein:s260986"
      - "Kinderradio (D)___:tunein:s230573"
      - "Omega 105.1 FM (Costa Rica)___:tunein:s82770"
      # - "Radio Pucki:s101757"
      # - "Radio TEDDY:s80044"


input_number:
  ledstrip_animation_speed:
    name: LEDstrip Animation Speed
    initial: 150
    min: 1
    max: 150
    step: 10
  outside_temp_diff:
    name: Outside to inside temperature difference
    initial: 1
    min: 0
    max: 360

notify: !include notify.yaml

scene: !include scenes.yaml

script: !include_dir_named scripts/

automation: !include_dir_merge_list automations/

# via https://github.com/arsaboo/\
# homeassistant-config/blob/01ed7ded33f7cc64ad878f123d3f2118dd77ba07/configuration.yaml#L288
logger:
  # levels: notset, debug, info, warn, warning, error, fatal, critical
  default: warn
  logs:
    homeassistant.components.notify.yessssms: debug
    homeassistant.components.notify.xmpp: info
    homeassistant.components.device_tracker.gpslogger: debug
    homeassistant.components.gpslogger: debug
    homeassistant.core: warn
    miio.device: critical
    homeassistant.components.vacuum.xiaomi_miio: critical
    # supress 'unparsed data' WARNING from AndroidIPCam
    urllib3.connectionpool: critical


input_boolean: !include input_booleans.yaml

input_datetime:
  time_wakeup_lights:
    name: Time for wakeup lights
    has_date: false
    has_time: true
    # initial: "6:43"
