---
# Sqlite really pounded the SD-card of my Raspberry Pi, it broke...
# trying external USB-stick as sqlite data store didn't work. That failed...
# postgres works much better, with faster startup times.
# db_url: !secret external_sqlite_url
db_url: !secret postgres_url
purge_keep_days: 5
purge_interval: 1
# db_url: !secret mariadb_url
