---
# fixme setup with new router
# - platform: luci
#   host: !secret router_IP
#   username: !secret router_user
#   password: !secret router_pwd
#   track_new_devices: false

# - platform: gpslogger
# password: !secret gps_logger_pwd

# - platform: nmap_tracker
#   hosts: !secret local_tracking_subnet
#   exclude: !secret dont_scan_hosts
#   scan_options: " --privileged -sP "
