---
testinger:
  initial: false

vacuum_bot_auto:
  initial: true
  name: "automatisch staubsaugen"
  icon: mdi:auto-fix

flo_at_home:
  initial: false

tine_at_home:
  initial: false

enable_red_button:
  icon: mdi:volume-mute
