---
- platform: group
  name: WZ Led strips
  entities:
    - light.ledstrip
    - light.lightstrip2
    - light.tv_light
    - light.wz_vitrine
    - light.gateway_light_286c07fa1faa
    # - light.wordclock


- platform: mqtt
  name: "TV light"
  # command_topic: "/br38/sonoff/switch/SONOFF_A751BC/relay/0"
  # state_topic: "/br38/sonoff/switch/SONOFF_A751BC/relay/0"
  command_topic: "cmnd/DVES_33C0B2/POWER"
  state_topic: "stat/DVES_33C0B2/POWER"
  payload_on: "ON"
  payload_off: "OFF"
  availability_topic: "tele/DVES_33C0B2/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  rgb_command_topic: "cmnd/DVES_33C0B2/Color"
  rgb_state_topic: "stat/DVES_33C0B2/RESULT"
  rgb_value_template: "{{value_json.Color.split(',')[0:3]|join(',')}}"
  brightness_command_topic: "cmnd/DVES_33C0B2/Dimmer"
  brightness_state_topic: "stat/DVES_33C0B2/RESULT"
  brightness_value_template: "{{value_json.Dimmer}}"
  brightness_scale: 100
  effect_command_topic: "cmnd/DVES_33C0B2/Scheme"
  effect_state_topic: "stat/DVES_33C0B2/RESULT"
  effect_value_template: "{{value_json.Scheme}}"
  effect_list:
    - "0 Solid"
    - "2 Rainbow"
    - "4 Rainbow random"
  optimistic: false
  # retain: true

- platform: mqtt
  name: "lightstrip2"
  # command_topic: "/br38/sonoff/switch/SONOFF_A751BC/relay/0"
  # state_topic: "/br38/sonoff/switch/SONOFF_A751BC/relay/0"
  command_topic: "cmnd/DVES_33C018/POWER"
  state_topic: "stat/DVES_33C018/POWER"
  payload_on: "ON"
  payload_off: "OFF"
  availability_topic: "tele/DVES_33C018/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  rgb_command_topic: "cmnd/DVES_33C018/Color"
  rgb_state_topic: "stat/DVES_33C018/RESULT"
  rgb_value_template: "{{value_json.Color.split(',')[0:3]|join(',')}}"
  brightness_command_topic: "cmnd/DVES_33C018/Dimmer"
  brightness_state_topic: "stat/DVES_33C018/RESULT"
  brightness_value_template: "{{value_json.Dimmer}}"
  brightness_scale: 100
  effect_command_topic: "cmnd/DVES_33C018/Scheme"
  effect_state_topic: "stat/DVES_33C018/RESULT"
  effect_value_template: "{{value_json.Scheme}}"
  effect_list:
    - "0 Solid"
    - "2 Rainbow"
    - "4 Rainbow random"
  optimistic: false
  # retain: true

- platform: mqtt
  name: "wz vitrine"
  # command_topic: "/br38/sonoff/switch/SONOFF_A751BC/relay/0"
  # state_topic: "/br38/sonoff/switch/SONOFF_A751BC/relay/0"
  command_topic: "cmnd/DVES_33BDB1/POWER"
  state_topic: "stat/DVES_33BDB1/POWER"
  payload_on: "ON"
  payload_off: "OFF"
  availability_topic: "tele/DVES_33BDB1/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  rgb_command_topic: "cmnd/DVES_33BDB1/Color"
  rgb_state_topic: "stat/DVES_33BDB1/RESULT"
  rgb_value_template: "{{value_json.Color.split(',')[0:3]|join(',')}}"
  brightness_command_topic: "cmnd/DVES_33BDB1/Dimmer"
  brightness_state_topic: "stat/DVES_33BDB1/RESULT"
  brightness_value_template: "{{value_json.Dimmer}}"
  brightness_scale: 100
  effect_command_topic: "cmnd/DVES_33BDB1/Scheme"
  effect_state_topic: "stat/DVES_33BDB1/RESULT"
  effect_value_template: "{{value_json.Scheme}}"
  effect_list:
    - "0 Solid"
    - "2 Rainbow"
    - "4 Rainbow random"
  optimistic: false
  # retain: true


- platform: mqtt
  name: "LEDstrip"
  command_topic: "esp8266/mqttstrip/setpower"
  state_topic: "esp8266/mqttstrip/setpowerpub"
  rgb_state_topic: "esp8266/mqttstrip/setcolorpub"
  rgb_command_topic: "esp8266/mqttstrip/setcolor"
  brightness_state_topic: "esp8266/mqttstrip/setbrightnesspub"
  brightness_command_topic: "esp8266/mqttstrip/setbrightness"
  optimistic: false
  retain: true
# - platform: mqtt
#   name: 'B1 Light TEST'
#   state_topic: '/br38/sonoff/light/SONOFF_B1_8677F2/relay/0'
#   command_topic: '/br38/sonoff/light/SONOFF_B1_8677F2/relay/0/set'
#   payload_on: 1
#   payload_off: 0
#   rgb_state_topic: '/br38/sonoff/light/SONOFF_B1_8677F2/color'
#   rgb_command_topic: '/br38/sonoff/light/SONOFF_B1_8677F2/color/set'
#   rgb: true
#   optimistic: false
#   color_temp: true
#   color_temp_command_topic: '/br38/sonoff/light/SONOFF_B1_8677F2/mired/set'
#   brightness: true
#   brightness_command_topic:
# '/br38/sonoff/light/SONOFF_B1_8677F2/brightness/set'
#   brightness_state_topic: '/br38/sonoff/light/SONOFF_B1_8677F2/brightness'
#   white_value: true
#   white_value_command_topic:
# '/br38/sonoff/light/SONOFF_B1_8677F2/channel/3/set'
#   white_value_state_topic: '/br38/sonoff/light/SONOFF_B1_8677F2/channel/3'


- platform: mqtt
  name: "wordclock"
  command_topic: "/wordclock-01201b00/wordclock/command"
  rgb_state_topic: "/wordclock-01201b00/wordclock/color"
  rgb_command_topic: "/wordclock-01201b00/wordclock/color"
  brightness_command_topic: "/wordclock-01201b00/wordclock/brightness"
  retain: true
