---
- platform: kodi
  host: !secret kodi_IP
  port: !secret kodi_port
  name: "osmc-Waldo"
  turn_on_action:
    service: wake_on_lan.send_magic_packet
    data:
      mac: !secret kodi_mac_address
      broadcast_address: !secret broadcast_IP
  #  service: media_player.kodi_call_method
  #  data:
  #    entity_id: media_player.kodi
  #    method: Addons.ExecuteAddon
  #    addonid: script.json-cec
  #    params:
  #      command: activate
  turn_off_action:
    #  - service: media_player.media_stop
    #    data:
    #      entity_id: media_player.kodi
    - service: media_player.kodi_call_method
      data:
        entity_id: media_player.kodi
        method: System.suspend
        # method: Addons.ExecuteAddon
        # addonid: script.json-cec
        # params:
        #  command: standby
#  turn_off_action: none

# not working as expected... put asleep
# - platform: samsungtv
#   # UE55MU6170UXZG
#   # requires pip3 install websocket-client
#   host: !secret samsung_smart_tv
#   # mac: !secret samsung_smart_tv_mac
#   port: 8001
#   name: "TV"

- platform: snapcast
  host: !secret snapcast_main_ip
- platform: mpd
  host: !secret mpd_main_ip
  port: 6601
