---
- name: Flo
  id: flo0001
  user_id: !secret flo_user_id
  device_trackers:
    - device_tracker.nokia_pnxgam88c1104874_2
    - !secret flo_phone_tracker
    - device_tracker.flo_laptop
    - device_tracker.flo_laptop2
    # - device_tracker.gpslogger
# - name: tine
#   id: tine0001
#   user_id: !secret tine_user_id
