---
- name: All on
  entities:
    switch.tradfri_outlet: true
    switch.wz_light_2: true
    switch.wz_light_3: true
    # switch.christbaum: true
    switch.esstisch_switch: true
    light.wz_vitrine:
      state: true
      brightness_pct: 100
      rgb_color: [0, 69, 108]
    light.lego_lampe:
      state: true
      color_temp: 454.54
      brightness: 255
    light.tradfri_bulb_e27_ws_opal_980lm:
      state: true
      color_temp: 454.54
      brightness: 254
    light.tradfri_bulb_e27_ws_opal_980lm_2:
      state: true
    light.tv_light:
      state: true
      brightness_pct: 95
      rgb_color: [255, 255, 255]
    light.ledstrip:
      state: true
      brightness: 254
      rgb_color: [0, 69, 108]
    light.lightstrip2:
      state: true
      brightness: 254
      rgb_color: [0, 69, 108]

- name: All off
  entities:
    switch.tradfri_outlet: false
    # switch.wz_light_2: false
    # switch.wz_light_3: false
    # switch.christbaum: false
    light.tv_light: false
    switch.esstisch_switch: false
    light.wz_vitrine:
      state: false
    light.lego_lampe:
      state: false
    light.tradfri_bulb_e27_ws_opal_980lm:
      state: false
    light.ledstrip:
      state: false
    light.tradfri_bulb_e27_ws_opal_980lm_2:
      state: false
    light.gateway_light_286c07fa1faa:
      state: false
    light.lightstrip2:
      state: false

- name: WZ Movies
  entities:
    switch.tradfri_outlet: false
    switch.wz_light_2: true
    switch.wz_light_3: true
    # switch.christbaum: false
    switch.esstisch_switch: false
    light.lego_lampe:
      state: true
      color_temp: 454.54
      brightness: 9
    light.tradfri_bulb_e27_ws_opal_980lm:
      state: false
    light.wz_vitrine:
      state: true
      brightness_pct: 15
      rgb_color: [0, 9, 38]
    light.tv_light:
      state: true
      brightness_pct: 15
      rgb_color: [0, 9, 38]
    light.lightstrip2:
      state: true
      brightness_pct: 15
      rgb_color: [0, 9, 38]
    light.ledstrip:
      state: true
      brightness: 55
      rgb_color: [0, 151, 205]
    light.gateway_light_286c07fa1faa:
      state: true
      brightness: 255
      rgb_color: [0, 34, 128]
    light.wordclock:
      state: true
      brightness: 33
      rgb_color: [0, 185, 255]

- name: WZ Movies 2
  entities:
    switch.tradfri_outlet: false
    switch.wz_light_2: true
    switch.wz_light_3: true
    # switch.christbaum: false
    switch.esstisch_switch: false
    light.tradfri_bulb_e27_ws_opal_980lm:
      state: false
    light.lego_lampe:
      state: true
      color_temp: 454.54
      brightness: 9
    light.wz_vitrine:
      state: true
      brightness_pct: 15
      rgb_color: [0, 9, 38]
    light.tv_light:
      state: true
      brightness_pct: 15
      rgb_color: [0, 90, 255]
    light.lightstrip2:
      state: true
      brightness_pct: 15
      rgb_color: [0, 90, 255]
    light.ledstrip:
      state: true
      brightness: 90
      rgb_color: [0, 69, 108]
    light.gateway_light_286c07fa1faa:
      state: false
    light.wordclock:
      state: true
      brightness: 33
      rgb_color: [0, 185, 255]

- name: WZ Movies 3
  entities:
    switch.tradfri_outlet: true
    switch.wz_light_2: true
    switch.wz_light_3: true
    light.tv_light: false
    # switch.christbaum: false
    switch.esstisch_switch: false
    light.ledstrip:
      state: true
      brightness: 9
      rgb_color: [228, 48, 0]
    # input_select.ledstrip_effect: Solid
    light.lego_lampe:
      state: true
      color_temp: 454.54
      brightness: 20
    light.tradfri_bulb_e27_ws_opal_980lm:
      state: false
    light.gateway_light_286c07fa1faa:
      state: false
    light.wordclock:
      state: true
      brightness: 33
      rgb_color: [0, 185, 255]

- name: Blue
  entities:
    switch.tradfri_outlet: false
    switch.wz_light_2: true
    # switch.wz_light_3: false
    # switch.christbaum: false
    switch.esstisch_switch: false
    light.lego_lampe:
      state: true
      rgb_color: [0, 151, 205]
      brightness: 40
    light.wz_vitrine:
      state: true
      brightness_pct: 15
      rgb_color: [0, 9, 38]
    light.tv_light:
      state: true
      brightness_pct: 55
      rgb_color: [0, 90, 255]
    light.lightstrip2:
      state: true
      brightness_pct: 15
      rgb_color: [0, 90, 255]
    light.ledstrip:
      state: true
      brightness: 155
      rgb_color: [0, 151, 205]
    light.gateway_light_286c07fa1faa:
      state: true
      brightness: 255
      rgb_color: [0, 34, 128]
    light.wordclock:
      state: true
      brightness: 33
      rgb_color: [0, 185, 255]

- name: Green
  entities:
    switch.tradfri_outlet: true
    switch.wz_light_2: true
    switch.wz_light_3: true
    switch.esstisch_switch: true
    light.lego_lampe:
      state: true
      color_temp: 454.54
      brightness: 255
    light.tradfri_bulb_e27_ws_opal_980lm:
      state: true
      color_temp: 373.412
      brightness: 145
    light.wz_vitrine:
      state: true
      brightness_pct: 15
      rgb_color: [20, 200, 0]
    light.tv_light:
      state: true
      brightness_pct: 80
      rgb_color: [20, 200, 0]
    light.lightstrip2:
      state: true
      brightness_pct: 15
      rgb_color: [20, 200, 0]
    light.ledstrip:
      state: true
      brightness: 255
      rgb_color: [5, 149, 0]
    light.gateway_light_286c07fa1faa:
      state: true
      brightness: 255
      rgb_color: [4, 111, 0]
    light.wordclock:
      state: true
      brightness: 200
      rgb_color: [0, 255, 0]


- name: Red
  entities:
    switch.tradfri_outlet: false
    switch.wz_light_2: true
    switch.wz_light_3: true
    switch.esstisch_switch: false
    light.lego_lampe:
      state: true
      rgb_color: [255, 0, 0]
      brightness: 150
    light.tradfri_bulb_e27_ws_opal_980lm:
      state: false
    light.wz_vitrine:
      state: true
      brightness_pct: 15
      rgb_color: [250, 0, 0]
    light.tv_light:
      state: true
      brightness_pct: 80
      rgb_color: [250, 0, 0]
    light.lightstrip2:
      state: true
      brightness_pct: 15
      rgb_color: [250, 0, 0]
    light.ledstrip:
      state: true
      brightness: 255
      rgb_color: [255, 20, 0]
    light.gateway_light_286c07fa1faa:
      state: true
      brightness: 255
      rgb_color: [255, 20, 0]
    light.wordclock:
      state: true
      brightness: 50
      rgb_color: [255, 0, 0]

- name: WZ Fireplace
  entities:
    switch.tradfri_outlet: false
    switch.wz_light_2: true
    switch.wz_light_3: true
    # switch.christbaum: false
    switch.esstisch_switch: false
    light.lego_lampe:
      state: true
      color_temp: 454.54
      brightness: 20
    light.wz_vitrine: false
    light.tv_light: false
    light.ledstrip:
      state: true
      brightness: 9
      rgb_color: [228, 48, 0]
    # input_select.ledstrip_effect: Solid
    light.gateway_light_286c07fa1faa:
      state: true
      brightness: 122
      rgb_color: [182, 39, 0]
    light.tradfri_bulb_e27_ws_opal_980lm:
      state: true
      color_temp: 454.54
      transition: 30
      brightness: 40
    light.wordclock:
      state: true
      brightness: 50
      rgb_color: [255, 255, 255]
    script.fireplace:
      state: true
      # #source: "https://www.youtube.com/watch?v=quYru3pzhYo&t=120"
      #   sequence:
      #     #source: "https://www.youtube.com/watch?v=quYru3pzhYo&t=120"
      # service: media_player.kodi_call_method
      #   data:
      #     entity_id: media_player.kodi
      #     method: Player.Open
      #     #addonid: script.json-cec
      #     item:
      # TODO try:
      # curl -s --data-binary '{"jsonrpc":"2.0","id":"1","method":"Player.Open",
      # file: "plugin://plugin.video.youtube/?action=play_video&\
      # videoid=quYru3pzhYo&t=120"
      # "params":{"item":{"file":"plugin://plugin.video.youtube/
      # ?action=play_video&videoid=YOUTUBE_VIDEO_ID"}}}'
      # -H 'content-type: application/json;' http://KODISERVERIP:KODIPORT/\
      # jsonrpc

- name: Just Fire
  entities:
    script.fireplace:
      state: true
