---
home_url: "https://myhomeismycastle.duckdns.org"
name_home: Home
zone1_name: zone1
zone2_name: zone2
zone3_name: zone3
zone4_name: zone4
api_password: password
tradfri_ip: 192.168.0.2
lat: 0.0
lon: 0.0
lat_zone2: 2.0
lon_zone2: 2.0
lat_zone3: 3.0
lon_zone3: 3.0
lat_zone4: 4.0
lon_zone4: 4.0
mqtt_user: homeassistant
mqtt_pwd: password
local_tracking_subnet: 192.168.0.0/24
dont_scan_hosts: 192.168.0.5
router_IP: 192.168.0.1
router_user: admin
router_pwd: admin
xmpp_user: user@xmpp.org
xmpp_pwd: password
xmpp_recipient: user@xmpp.org
owm_api_key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
darksky_api_key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
mariadb_pass: password
mariadb_host: localhost
mariadb_url: mysql://hass:password@localhost/homeassistant
external_sqlite_url: sqlite:///home/homeassistant/hass.db
postgres_url: postgresql://user:password@SERVER_IP/DB_NAME
flo_phone_tracker: "device_tracker.testtesttest"
flo_phone_label: "FloPhone"
tine_phone_tracker: device_tracker.tine_phone
yesss_user: "06641234567"
yesss_pw: "password"
yesss_sms_flo: "06641234567"
feinstaub_URL: http://192.168.0.3/sensor/feinstaub.json
elec_IP: 192.168.0.4
elec_mac_address: "de:ad:be:ef:ca:fe"
elec_port: 8080
kodi_IP: 192.168.0.4
kodi_mac_address: "de:ad:be:ef:ca:fe"
kodi_port: 8000
mopidy_webclient_url: http://192.168.0.111:6681/musicbox_webclient
broadcast_IP: "192.168.0.255"
android_ipc_user: "user"
android_ipc_pass: "password"
android_ipc_video_path: "http://192.168.0.5:8080/video"
android_ipc_photo_path: "http://192.168.0.5:8080/photo.jpg"
android_ip_cam_ip: "192.168.0.5"
raspy_motioneye1_path: "http://192.168.1.100:8081/"
raspy_motioneye1_pic: "http://192.168.1.100:80/picture/1/current/"
raspy_motioneye1_user: "user"
raspy_motioneye1_pass: "password"
ble_tacker: "device_tracker.ble_deadbeefcafe"
flo_phone_battery: "sensor.flo_phone_bat"
flo_user_id: "321da28e-b5c0-4c61-8707-9e3f4efeef07"
tine_user_id: "b36541f9-0a72-4183-9a0d-75079ad4e3f7"
raspi_camera: "http://192.168.0.6:8554/"
samsung_smart_tv: "192.168.0.7"
samsung_smart_tv_mac: "de:ad:be:ef:ca:fe"
xiaomi_gw_mac: "de:ad:c0:ff:ee:00"
xiaomi_gw_key: "xxxxxxxxxxxxxxxx"
xiaomi_vacuum_key: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
snapcast_main_ip: 192.168.0.8
mpd_main_ip: 192.168.0.9
gps_logger_pwd: secret_password
influx_user: homeassistant
influx_pass: password
influx_host: myinflux.example.com
influx_port: 8086
grafana_link_url: https://grafana.host.example.com/d/asdfasdf/homeassistant?refresh=1m&orgId=1
gitlab_API_private_token: "XXXXXXXXXXXXXXXXXXXXXXX"
waze_home_coord: 20.0,22.0
waze_rosemountain_coord: 22.123,22.456
waze_work_coord: 22.789,23.123
waze_stein_coord: 25.0,26.0
nuki_host: "192.168.1.15"
nuki_token: "secret"
wallpanel_stream: "http://192.168.0.77:1829/camera/stream"
