---
# not really used anymore...
- platform: rpi_rf
  gpio: 17
  switches:
    rf_light_1:
      # previously wz_light_1:
      code_on: 4456469
      code_off: 4456468
      pulselength: 367
      protocol: 1
      signal_repetitions: 25
      # friendly_name: "grosse Stehlampe"
    wz_light_2:
      code_on: 4472853
      code_off: 4472852
      pulselength: 367
      protocol: 1
      # friendly_name: "Lampe Couch"
    wz_light_3:
      code_on: 4460565
      code_off: 4460564
      pulselength: 367
      protocol: 1
      # friendly_name: "Lego Lampe"
    wz_light_4:
      code_on: 69909
      code_off: 69908
      pulselength: 500
      protocol: 1
    wz_light_5:
      code_on: 70677
      code_off: 70676
      pulselength: 500
      protocol: 1
    wz_light_6:
      code_on: 70933
      code_off: 70932
      pulselength: 500
      protocol: 1

- platform: mqtt
  name: "Christbaum"
  command_topic: "cmnd/tasmota_plug1/POWER"
  state_topic: "stat/tasmota_plug1/POWER"
  payload_on: "ON"
  payload_off: "OFF"
  optimistic: false

- platform: mqtt
  name: "gosund_042CFB"
  command_topic: "cmnd/tasmota_042CFB/POWER"
  state_topic: "stat/tasmota_042CFB/POWER"
  payload_on: "ON"
  payload_off: "OFF"
  optimistic: false

- platform: mqtt
  name: "gosund_042C5F"
  command_topic: "cmnd/tasmota_042C5F/POWER"
  state_topic: "stat/tasmota_042C5F/POWER"
  payload_on: "ON"
  payload_off: "OFF"
  optimistic: false

- platform: mqtt
  name: "gosund_042143"
  command_topic: "cmnd/tasmota_042143/POWER"
  state_topic: "stat/tasmota_042143/POWER"
  payload_on: "ON"
  payload_off: "OFF"
  optimistic: false


- platform: mqtt
  name: "gosund_036643"
  command_topic: "cmnd/tasmota_036643/POWER"
  state_topic: "stat/tasmota_036643/POWER"
  payload_on: "ON"
  payload_off: "OFF"
  optimistic: false


# - platform: mqtt
#   name: "christmas lights"
#   friendly_name: "Weihnachtsbeleuchtung"
#   command_topic: "/br38/sonoff/switch/SONOFF_BASIC_3EFBC1/relay/0/set"
#   state_topic:   "/br38/sonoff/switch/SONOFF_BASIC_3EFBC1/relay/0"
#   payload_on: "1"
#   payload_off: "0"
#   optimistic: false

- platform: mqtt
  name: "Ventilator"
  # friendly_name: "Ventilator"
  command_topic: "cmnd/sonoff_3EFBC1/POWER"
  state_topic: "stat/sonoff_3EFBC1/POWER"
  payload_on: "ON"
  payload_off: "OFF"
  optimistic: false

- platform: mqtt
  name: "Rundumleuchte"
  # friendly_name: "Rundumleuchte"
  command_topic: "cmnd/sonoff_A7FEB5/POWER"
  state_topic: "stat/sonoff_A7FEB5/POWER"
  payload_on: "ON"
  payload_off: "OFF"
  optimistic: false
  retain: false

- platform: mqtt
  name: "Kitchen"
  # friendly_name: "Küche"
  command_topic: "cmnd/br38/shelly-kitchen/POWER"
  state_topic: "stat/br38/shelly-kitchen/POWER"
  payload_on: "ON"
  payload_off: "OFF"
  availability_topic: "tele/br38/shelly-kitchen/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  optimistic: false
  retain: false
- platform: mqtt
  name: "Kitchen light1"
  # friendly_name: "Licht 1"
  command_topic: "cmnd/sonoff_kitchen1/POWER"
  state_topic: "stat/sonoff_kitchen1/POWER"
  payload_on: "ON"
  payload_off: "OFF"
  availability_topic: "tele/sonoff_kitchen1/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  optimistic: false
  retain: false
- platform: mqtt
  name: "SONOFF1"
  # friendly_name: "SONOFF1"
  command_topic: "/br38/sonoff/switch/SONOFF_BASIC_A7FEB5/relay/0/set"
  state_topic: "/br38/sonoff/switch/SONOFF_BASIC_A7FEB5/relay/0"
  payload_on: "1"
  payload_off: "0"
  optimistic: false

- platform: mqtt
  name: "sonoff_s20_0954"
  # friendly_name: "Licht S20 0954"
  command_topic: "cmnd/sonoff_s20_0954/POWER"
  state_topic: "stat/sonoff_s20_0954/POWER"
  payload_on: "ON"
  payload_off: "OFF"
  optimistic: false
  # retain: true
- platform: mqtt
  name: "sonoffS20_6448"
  # friendly_name: "S20 6448"
  command_topic: "cmnd/sonoff_s20_6448/POWER"
  state_topic: "stat/sonoff_s20_6448/POWER"
  payload_on: "ON"
  payload_off: "OFF"
  optimistic: false
  # retain: true
