---
- alias: "Button 1 All off"
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d000128afa3
        click_type: long_click_press
  action:
    service: scene.turn_on
    entity_id: scene.all_off

- alias: "Button 1 christmas tree"
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d000128afa3
      click_type: single
  action:
    service: switch.toggle
    data:
      entity_id: switch.christbaum

- alias: "Button 1 all on"
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d000128afa3
      click_type: double
  action:
    service: scene.turn_on
    data:
      entity_id: scene.all_on
