- alias: "Button 1 All off"
  trigger:
    - platform: event
      event_type: click 
      event_data:
        entity_id: binary_sensor.switch_158d000128afa3
        click_type: long_click_press
  action:
    service: scene.turn_on
    entity_id: scene.all_off

- alias: "Button 1 lego lamp"
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d000128afa3
      click_type: single
  action:
    service: light.toggle
    data:
      entity_id: light.lego_lampe
      # color_temp: 450
      # brightness: 150

- alias: "Button 1 all on"
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d000128afa3
      click_type: double
  action:
    service: scene.turn_on
    data:
      entity_id: scene.all_on


