---
- alias: "toggle living room lights"
  initial_state: True
  trigger:
    - platform: event
      event_type: click
      event_data:
        # xiaomi button n°3
        entity_id: binary_sensor.switch_158d00016bf562
        click_type: single
  action:
    - service: light.toggle
      data:
        entity_id: light.tradfri_bulb_e27_ws_opal_980lm
    - service: switch.toggle
      data:
        entity_id: switch.wz_light_1

- alias: "toggle big light"
  initial_state: True
  trigger:
    - platform: event
      event_type: click
      event_data:
        # xiaomi button n°3
        entity_id: binary_sensor.switch_158d00016bf562
        click_type: double
  action:
    - service: switch.toggle
      data:
        entity_id: switch.wz_light_1

- alias: "turn off living room lights"
  initial_state: True
  trigger:
    - platform: event
      event_type: click
      event_data:
        # xiaomi button n°3
        entity_id: binary_sensor.switch_158d00016bf562
        click_type: long_click_press
  action:
    - service: light.turn_off
      data:
        entity_id: light.tradfri_bulb_e27_ws_opal_980lm
    - service: switch.turn_off
      data:
        entity_id: switch.wz_light_1
