---
- alias: "Christmas lights on"
  trigger:
    platform: sun
    event: sunset
    offset: "00:20:00"
  action:
    service: homeassistant.turn_on
    entity_id:
      - switch.sonoffs20_6448
        #      - switch.christmas_lights
- alias: "Christmas lights off"
  trigger:
    platform: sun
    event: sunset
    offset: "07:05:00"
  action:
    service: homeassistant.turn_off
    entity_id:
      - switch.sonoffs20_6448
