- alias: "coming home (turn on WZ light)"
  hide_entity: False
  trigger:
    platform: state
    entity_id: sensor.flo_home
    to: 'home'
  condition:
    condition: numeric_state
    entity_id: sensor.balkon_light_level
    below: 25
  action:
    - service: homeassistant.turn_on
      entity_id:
        - switch.wz_light_1
        - switch.wz_light_2
