---
- alias: "coming home (turn on VZ light)"
  hide_entity: false
  trigger:
    platform: state
    entity_id: binary_sensor.wohnungstuer
    from: 'off'
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sun.sun
        state: "below_horizon"
        for:
          minutes: 10
      - condition: state
        entity_id: light.vzlicht_level
        state: "off"
        for:
          minutes: 1
  action:
    - service: homeassistant.turn_on
      entity_id:
        - light.vzlicht_level
