- alias: "coming home (turn on WZ light)"
  hide_entity: False
  trigger:
    platform: state
    entity_id: sensor.flo_home
    to: 'home'
  condition:
    condition: numeric_state
    entity_id: sensor.balkon_light_level
    below: 25
  action:
    - service: homeassistant.turn_on
      entity_id:
        - switch.wz_light_1
    - service: light.turn_on
      data:
        entity_id: light.tradfri_bulb_e27_ws_opal_980lm
        color_temp: 454.54
        brightness: 254
        transition: 60
