- alias: "Sunset 2"
  initial_state: True
  trigger:
    platform: numeric_state
    entity_id: sensor.balkon_light_level
    below: 20
    for:
      minutes: 5
  condition:
    condition: state
#    entity_id: group.all_devices
    entity_id: sensor.flo_home
    state: "home"
  action:
    service: script.sunset
