- alias: "Sunset 2"
  initial_state: False
  trigger:
    platform: numeric_state
    entity_id: sensor.balkon_light_level
    below: 25
    for:
      minutes: 5
  condition:
    condition: state
    entity_id: group.all_devices
    state: "home"
  action:
    service: script.sunset
