- alias: "auto media player lighting"
  initial_state: False
  trigger:
    - platform: state
      entity_id: media_player.osmcwaldo
      to: 'playing'
#      from: 'idle'
      for:
        minutes: 2
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
  action:
      service: scene.turn_on
      entity_id: scene.wz_movies
