- alias: "wakeup7"
  hide_entity: False
  initial_state: False
  trigger:
    platform: time
    hours: 6
    minutes: 57
    seconds: 10
  condition:
    condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
    service: homeassistant.turn_on
    entity_id:
      - switch.wz_light_1
      - switch.wz_light_2
#      - tradfri_bulb_e27_ws_opal_980lm
        # data:
        #   - brightness: 254,
        #   - transition: 240
