- alias: "wakeup lights"
  hide_entity: False
  initial_state: True
  trigger:
    platform: time
    minutes: '/1'
    seconds: '10'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: binary_sensor.workday_sensor
        state: 'on'
      - condition: state
        entity_id: sensor.flo_home
        state: 'home'
      - condition: template
        value_template: "{{ 'true' if states.sensor.time.state.split(':')[0] |int == states.input_datetime.time_wakeup_lights.attributes.hour | int else 'false' }}"
      - condition: template
        value_template: "{{ 'true' if states.sensor.time.state.split(':')[1] |int == states.input_datetime.time_wakeup_lights.attributes.minute | int else 'false' }}"
  action:
    - service: light.turn_on
      data:
        entity_id: light.tradfri_bulb_e27_ws_opal_980lm
        color_temp: 454.54
        brightness: 254
        transition: 60
    # - service: notify.jabber
    #   data:
    #     title: ""
    #     message: "alarm triggered"
