---
- platform: template
  sensors:
    schloss_wohnungstuer:
      device_class: safety
      friendly_name: 'Wohnungstür'
      value_template: >-
        {%- if is_state("lock.br38", "locked") -%}
          False
        {%- else -%}
          True
        {%- endif -%}
      icon_template: >
        {% if is_state('lock.br38', 'locked') %}
          mdi:shield-check
        {% elif is_state('lock.br38', 'unlocked') %}
          mdi:lock-open-outline
        {% else %}
          mdi:lock-question
        {% endif %}
