---
esphome:
  name: rgbleds1
  platform: ESP8266
  board: d1_mini
  # on_boot:
  #   priority: -10
  #   then:
  #     - light.turn_on:
  #         id: light1
  #         brightness: 20%
  #         red: 0
  #         blue: 1
  #         green: 0.4

logger:

# Example configuration entry
light:
  - platform: neopixelbus
    id: light1
    type: GRB
    method: BIT_BANG
    variant: WS2812X
    pin: D1
    num_leds: 10
    name: "10 status leds"
    effects:
      # Customize parameters
      - random:
          name: "My Slow Random Effect"
          transition_length: 15s
          update_interval: 30s
      - random:
          name: "My Fast Random Effect"
          transition_length: 4s
          update_interval: 5s
      - random:
          name: "My Faster Random Effect"
          transition_length: 1.5s
          update_interval: 3s
      - addressable_rainbow:
      - addressable_rainbow:
          name: Rainbow Effect With Custom Values
          speed: 10
          width: 10
      - addressable_scan:
      - addressable_scan:
          name: Scan Effect With Custom Values
          move_interval: 100ms
      - addressable_twinkle:
      - addressable_twinkle:
          name: Twinkle Effect With Custom Values
          twinkle_probability: 5%
          progress_interval: 4ms
      - addressable_random_twinkle:
      - addressable_random_twinkle:
          name: Random Twinkle Effect With Custom Values
          twinkle_probability: 5%
          progress_interval: 32ms
mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_user
  password: !secret mqtt_pass

api:
  password: !secret api_pass_2

ota:
  password: !secret ota_pass

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass
